"""
generate_docs.py — Step 2 of the frontend pipeline.

Feeds page JSON into AI and generates:
  - docs/frontend/pages.md
"""

import os
import sys
import time
from typing import List

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from prompts.frontend_prompts import pages_md_prompt, pages_md_system
from shared.ai_client import AIConfig, call_ai


def generate_pages_md(
    pages: List[dict],
    output_path: str,
    config: AIConfig,
    no_ai: bool = False,
) -> None:
    """
    Generate pages.md — one section per frontend page/route.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    sys_msg  = pages_md_system()
    sections: List[str] = []

    for i, page in enumerate(pages):
        path      = page.get("path", "UNKNOWN")
        component = page.get("component", "UNKNOWN")

        print(f"    🖼️  [{i+1}/{len(pages)}] {path} ({component})")

        if no_ai or not config.use_ai:
            section = _skeleton_page(page)
        else:
            prompt  = pages_md_prompt(page)
            section = call_ai(prompt, config, system=sys_msg, max_tokens=1500)
            if section.startswith("[AI failed"):
                print(f"       ⚠️  AI failed — using skeleton")
                section = _skeleton_page(page)
            if config.delay > 0:
                time.sleep(config.delay)

        sections.append(section)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Frontend Pages Documentation\n\n")
        f.write("_Generated by doc_writer. One section per page/route._\n\n")
        f.write("---\n\n")
        for s in sections:
            f.write(s.strip() + "\n\n")

    print(f"  ✅ pages.md → {output_path}")


def _skeleton_page(page: dict) -> str:
    """No-AI fallback: structured markdown from extracted JSON."""
    path       = page.get("path", "UNKNOWN")
    component  = page.get("component", "UNKNOWN")
    layout     = page.get("layout", "UNKNOWN")
    children   = page.get("children", [])
    api_calls  = page.get("api_calls", [])
    state_mgmt = page.get("state_management", [])
    unknowns   = page.get("unknowns", [])

    children_md = "\n".join(f"- `{c}`" for c in children) or "None"
    state_md    = ", ".join(state_mgmt) if state_mgmt else "none"
    unknowns_md = "\n".join(f"- {u}" for u in unknowns) or "None"

    api_lines = []
    for call in api_calls:
        api_lines.append(
            f"- `{call.get('method','?')} {call.get('endpoint','UNKNOWN')}`  "
            f"← {call.get('called_from','?')} "
            f"via {call.get('composable', call.get('via','direct'))}"
        )
    api_md = "\n".join(api_lines) or "None detected"

    return (
        f"# Page: {path}\n\n"
        f"## Component\n`{component}`\n\n"
        f"## Layout\n{layout}\n\n"
        f"## Child Components\n{children_md}\n\n"
        f"## API Dependencies\n{api_md}\n\n"
        f"## State Management\n{state_md}\n\n"
        f"## Unknowns\n{unknowns_md}\n\n"
        f"---"
    )